# site name
prefixName: 小惠的
siteName: 博客
# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/profile/%E5%A4%B4%E5%83%8F.jpg
avatar: https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/profile/%E5%A4%B4%E5%83%8F.jpg
url: https://bietiaop.top
description: 小惠的博客，什么都有。
cdn:
pjax: 1
# 1开启
mathjax: 1

notice: false
lazyloadImg: https://cdn.jsdelivr.net/gh/xbclub/imageCDN//upload/20200306164050.gif
#seo优化设定
seo:
  #网站简介
  description: 小惠的博客，啥都有。
  #关键词
  keywords: 小惠,小惠的博客,学习,UP主,P主,二次元爱好者,动漫爱好者,宅男,技术分享,资源分享
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  笔记: {path: /book/, fa: fa-book}
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce },
    番组: {path: /bangumi/, fa: fa-film faa-vertical },
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  #赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /about/, fa: fa-leaf faa-wrench }
  友人帐: { path: /links/, fa: fa-link faa-shake }

#页脚信息
pagefooter: Copyright © 2020 小惠. All rights reserved.

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/xbclub/CDN@master/manifest/webp/1ac3fa3ef82c93a8d46384e256342711.webp
  - https://cdn.jsdelivr.net/gh/xbclub/CDN@master/manifest/webp/6f005cbc1865ff1b706aba57347988ab.webp
  - https://cdn.jsdelivr.net/gh/xbclub/CDN@master/manifest/webp/a5fa4f9db760f58fc48f03d66b4967f7.webp
  - https://cdn.jsdelivr.net/gh/xbclub/CDN@master/manifest/webp/b3e8dae89b950b940dc0edd1e8cc0566.webp
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318135357.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318135356.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318131030.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318131029.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318131028.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318131027.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318130821.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318130820.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318130819.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318123027.png
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318123026.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318123025.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318123024.jpg
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318122955.png
  - https://cdn.jsdelivr.net/gh/bietiaop/CDN@master/img/20200318122954.jpg

# 背景图片数量
bgn: 19
# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: https://space.bilibili.com/152308001, title: Bilibili, desc: 我的B站账号, img: https://i.loli.net/2020/03/14/Ynl326xGMOpsf84.jpg}
  - {url: /, title: 小惠的博客, desc: 主页, img: https://i.loli.net/2020/03/14/fRaZspS9w73Vkyn.jpg}


# your site build time or founded date (建站日期）
siteBuildingTime: 2020-3-14
#页脚显示网站已运行时间
runtime: true

#social  url, img PC端配置
social:
  github: {url: http://github.com/bietiaop, img: https://cdn.jsdelivr.net/gh/xbclub/staticCDN@0.6/img/social/github.png}
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  #wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  #zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: mailto:1527109126@qq.com, img: https://cdn.jsdelivr.net/gh/xbclub/staticCDN@0.6/img/social/email.svg}
  #wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/bietaiop, fa: fa-github, color: 333}
#  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1527109126&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  switch: false
  paypal: false
  alipay: false
  wechat: false
  wechatSQ: pic

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  switch: false
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer:
  switch: true
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: true
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: DDigLuE07XrEbjAVrtFfJL4Q-gzGzoHsz
v_appKey: lnLeDfzevap6S5fUlzeY4of9

#42cloud 计数器
readcounts: true

#不蒜子计数器
busuanzi:
  switch: false

#每日一言
hitokoto: true